### ISSUE TITLE
Need to handle partially submitted events 

### ISSUE THREAD

**Issue by Refal** [zalando-nakadi/kanadi#107]
If we send to nakadi List of events - they could be processed partially then Nakadi return 207 status code with [BatchItemResponse](https://nakadi.io/manual.html#definition_BatchItemResponse) in a response body.
Right now kanadi client treats 207 as a success that is wrong.

**Comment by mdedetrich** [comment]
Long story short, us interpreting 207 as a "success" is not wrong since its a 2xx status code. The exception here is 207 WebDAG, which can indicate partial failure. Technically speaking when using WebDAG the client needs to specify that they support partial failure in responses however this isn't the case for Nakadi.

I am implementing an automatic retry in the case of 207, however by default this will be turned off because there is a potential to send events out of order (and some people rely on this behavior)
