### ISSUE TITLE
Problem cannot be parsed

### ISSUE THREAD

**Issue by gchudnov** [zalando-nakadi/kanadi#168]
Hi

It looks the `Problem` data type cannot be parsed (for example [here](https://github.com/zalando-nakadi/kanadi/blob/master/src/main/scala/org/zalando/kanadi/api/package.scala#L73)).

The `Problem` case class has the [following structure](https://github.com/mdedetrich/webmodels/blob/master/shared/src/main/scala/org/mdedetrich/webmodels/Problem.scala#L29):

```
final case class Problem(`type`: String,
                         title: Option[String] = None,
                         status: Option[Int] = None,
                         detail: Option[String] = None,
                         instance: Option[String] = None,
                         extraFields: JsonObject = JsonObject.empty)
```

and as we can see `type` is a non-optional.

In the [documentation](https://nakadi.io/manual.html#definition_Problem) it is mandatory as well.

But the reality is different, the server never returns it (or stopped returning at some time):

```
{"title":"Forbidden","status":403,"detail":"Access on READ subscription:e1eeeb6d-1819-48de-924e-ded2fe983c9e denied"}

{"title":"Conflict","status":409,"detail":"Resetting subscription cursors request is still in progress"}
```

According the conversation in `Zalando ticket : ARUHA / issues / 118` there is an intention to fix the documentation, not the server.

In this way it might better either to update `webmodels` and make this field optional or import that datatype to kanadi and make the field optional. So the Problem can be parsed correctly.

**Comment by mdedetrich** [comment]
Hey @gchudnov , sorry for the long response (I am currently getting too many github notifications so sometimes it gets lost in the noise).

I currently have some (unsubmitted) work to better handle this, i.e. having a `ServerError` type which would have the following ADT
 - Problem
 - Json (if the error is not a valid `Problem` type, i.e. the `type` field is missing`)
 - String (if the response is not even a valid JSON)
 
 In the meantime, I would press Aruha to add a `type` field because it really is mandatory in the spec and also I do not see any reason why they shouldn't add the field because it won't break any clients (they can even add `about:blank` as a default if they can't point it to anything as per the RFC spec)
