### ISSUE TITLE
Null values are omitted when publishing events

### ISSUE THREAD

**Issue by diastremskii** [zalando-nakadi/kanadi#192]
By default, Kanadi omits all `null` values from the event JSON when publishing events because of [the default configuration](https://github.com/zalando-nakadi/kanadi/blob/0bf825533ace33d891ab96d3b0d11acd0fb24b89/src/main/scala/org/zalando/kanadi/api/package.scala#L25).

For example, when using a schema like
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Event",
    "type": "object",
    "properties": {
        "test": {
            "type": [
                "string",
                "null"
            ]
        }
    },
    "required": [
        "test"
    ]
}
```
An event with data `{"test": null}` is going to be successfully published when calling Nakadi directly, but it's going to fail when publishing through Kanadi, because the field `test` is going to be dropped.

**Comment by gchudnov** [comment]
Hi @TheBeastOfCaerbannog 
thanks for reporting an issue.

true, it might worth to add a way to configure null-propagation (?)

If we just enable null-propagation (without configuration), it might break the current behavior some apps might be relying on now, where null-values are _not_ propagated.

Another option could be - split the library and extract encoding / decoding but that will require lots of changes.
So will check the first option -- null-configuration.

If you have any other ideas, please let me know.

Thank you,
Grigorii

**Comment by TheBeastOfCaerbannog** [comment]
Hi @gchudnov,
Thank you for checking that on such short notice!

Yeah, definitely, giving an option to configure that would be great and would be a backward-compatible change if we keep the current configuration by default.

I think this logic was added to omit `null`'s from metadata/some other parts of the event (except the event data), because Nakadi doesn't accept `null`'s for some of the fields in metadata. But because `Parser` is recursive, the unexpected effect was that it also omits `null`'s from the event data itself.

**Comment by gchudnov** [comment]
closing as the issue was migrated to the internal repository
